java_binary(
  name = "MakeHeaderMap",
  srcs = ["MakeHeaderMap.java"],
  main_class = "tools.headermap.MakeHeaderMap",
  visibility = ["//visibility:public"],
  deps = [
    "//third_party/buck/src/com/facebook/buck/apple/clang:HeaderMap",
    "@com_google_code_findbugs//jar",
    "@com_google_guava_guava//jar",
  ],
)
